//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace НадёжностьЭлементов.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("НадёжностьЭлементов.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap iconsDel {
            get {
                object obj = ResourceManager.GetObject("iconsDel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Резисторы постоянные непроволочные
        ///Металлодиэлектрические (кроме прецизионных),Металлодиэлектрические прецизионные,Металлизированные
        ///&lt;1 кОм,[1; 100)кОм,[0.1; 1]МОм,≥1 МОм
        ///Композиционные пленочные
        ///≤10 МОм,&gt;10 МОм
        ///Композиционные объемные
        ///≤150 Ом,(0.15;10]кОм,(0.01;1]МОм
        ///
        ///Резисторы постоянные проволочные и металлофольговые
        ///Нагрузочные
        ///≤1 кОм,(1;10]кОм,(10;100]кОм.
        /// </summary>
        internal static string KR {
            get {
                return ResourceManager.GetString("KR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Конденсаторы постоянной емкости
        ///Керамические на номинальное напряжение менее 1600В,Керамические на номинальное напряжение 1600В и выше,Тонкопленочные с неорганическим диэлектриком,Стеклянные
        ///Конденсаторы подстроечные
        ///С твердым диэлектриком,Воздушные
        ///Сборки на основе конденсаторов
        ///Сборки на основе конденсаторов
        ///Конденсаторы и фильтры помехоподавляющие 
        ///Конденсаторы и фильтры помехоподавляющие .
        /// </summary>
        internal static string Гр_Подгр_конденсаторов {
            get {
                return ResourceManager.GetString("Гр_Подгр_конденсаторов", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Металлодиэлектрические (кроме прецизионных)
        ///0,5;1,2,5,10 и более
        ///Металлодиэлектрические прецизионные
        ///0,05;0,1;0,25;0,5;1,2,5,10.
        /// </summary>
        internal static string Допуск {
            get {
                return ResourceManager.GetString("Допуск", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Резисторы постоянные непроволочные
        ///Металлодиэлектрические (кроме прецизионных),Металлодиэлектрические прецизионные,Металлизированные
        ///0,35;0,40;0,45;0,51;0,58;0,65;0,72;0,81;0,90;1,00
        ///0,36;0,41;0,47;0,53;0,59;0,67;0,75;0,84;0,94;1,05
        ///0,37;0,42;0,48;,0,55;0,62;0,69;0,78;0,87;0,98;1,09
        ///Композиционные пленочные
        ///0,27;0,33;0,39;0,45
        ///0,29;0,35;0,41;0,48
        ///0,31;0,37;0,44;0,52
        ///Композиционные объемные
        ///0,44;0,47;0,50;0,54
        ///0,46;0,49;0,53;0,57
        ///0,49;0,52;0,56;0,61
        ///Резисторы постоянные проволочные и металлофоль [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Коэффициент_режима_резисторов {
            get {
                return ResourceManager.GetString("Коэффициент_режима_резисторов", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Резисторы постоянные непроволочные
        ///Металлодиэлектрические (кроме прецизионных)
        ///Р1-2*,Р1-3*,Р1-5*,Р1-9*,Р1-10*,Р1-33*
        ///0,05
        ///Р1-4,Р1-11,Р1-12,Р1-16,Р1-16П,С2-6,С2-23,С2-33М,С2-33,С2-33Н
        ///0,065
        ///С1-4
        ///0,1
        ///Р1-6,Р1-8,С2-10,С2-10а,С2-10б,С2-34,С2-34М
        ///0,04
        ///Металлодиэлектрические прецизионные
        ///С2-14,С2-29В,С2-36
        ///0,043
        ///Металлизированные
        ///С6-2,С6-3,С6-4,С6-5,С6-6,С6-7,С6-8,С6-9
        ///0,04
        ///Композиционные пленочные
        ///КЭВ,С3-12,С3-14,С3-15
        ///0,03
        ///Композиционные объемные
        ///С4-2,ТВО,С4-3,УНУ*
        ///0,04
        ///Резисторы постоянные [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ЛямбдаШтрихБ {
            get {
                return ResourceManager.GetString("ЛямбдаШтрихБ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Резисторы постоянные непроволочные
        ///Металлодиэлектрические (кроме прецизионных),Металлодиэлектрические прецизионные,Металлизированные,Композиционные пленочные,Композиционные объемные
        ///
        ///Резисторы постоянные проволочные и металлофольговые
        ///Нагрузочные.
        /// </summary>
        internal static string Наименование_группы {
            get {
                return ResourceManager.GetString("Наименование_группы", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Керамические на номинальное напряжение менее 1600В
        ///КМ-4Б,КМ-5Б,К10-17а,К10-17б,К10-17в,К10-26,К10-42
        ///Керамические на номинальное напряжение 1600В и выше
        ///КВИ-1,КВИ-2,КВИ-3,К15-5,К15-12а,К15-12б,К15-13
        ///Тонкопленочные с неорганическим диэлектриком
        ///К26-4*
        ///Стеклянные
        ///К21-7
        ///С твердым диэлектриком
        ///КТ4-25,КТ4-27,КТ4-30*,КТ4-33*
        ///Воздушные
        ///КПВМ,КТ2-17-21,КТ2-50,КТ2-51
        ///Сборки на основе конденсаторов
        ///Б18,Б18А
        ///Конденсаторы и фильтры помехоподавляющие
        ///КБП,КБПС-Ф,КЗ,Б14,Б23А,Б23Б.
        /// </summary>
        internal static string Подрг_Типы_конденсаторов {
            get {
                return ResourceManager.GetString("Подрг_Типы_конденсаторов", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Справочник_конденсаторов {
            get {
                object obj = ResourceManager.GetObject("Справочник_конденсаторов", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Справочник_резисторов {
            get {
                object obj = ResourceManager.GetObject("Справочник_резисторов", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Металлодиэлектрические (кроме прецизионных)
        ///Р1-2*,Р1-3*,Р1-4,Р1-5*,Р1-6
        ///Металлодиэлектрические прецизионные
        ///С2-14,С2-29В,С2-36
        ///Металлизированные
        ///С6-2,С6-3,С6-4,С6-5,С6-6
        ///Композиционные пленочные
        ///КЭВ,С3-12,С3-14,С3-15
        ///Композиционные объемные
        ///С4-2,С4-3,ТВО,УНУ*
        ///Нагрузочные
        ///ПЭВТ,С5-35В,С5-36В,С5-37В,С5-40
        ///.
        /// </summary>
        internal static string Типы_изделий_по_подгруппам1 {
            get {
                return ResourceManager.GetString("Типы_изделий_по_подгруппам1", resourceCulture);
            }
        }
    }
}
